/* PHG design knowledge for Harmony's menu designer.
   Snapshot (2026-09-29) of phg_design: 104 principles with confidence >= 0.9 in the domains that govern a menu
   (menu design and engineering, typography, colour, accessibility, composition, gestalt, grid, identity, imagery,
   art direction), the active agent guidance, and the source list. Principle names are the rules themselves.
   Replace with a live read once a read-only accessor for phg_design is approved (migration draft). */

export const DESIGN_KNOWLEDGE = `PHG DESIGN KNOWLEDGE (from PHG's design knowledge base: peer-reviewed menu research — Yang et al. 2023 menu-design meta-analysis, Reynolds et al. eye-tracking scanpaths, Ngan et al. price-conscious gaze, Yang/Kimes/Sessarego price presentation, Magnini & Kim font and background colour; plus Albers, Bringhurst, Ruder, Hofmann, Müller-Brockmann, Gerstner, Vignelli, Lupton, Dondis, Tufte, MIT OpenCourseWare, Yale School of Art, AIGA, Letterform Archive, W3C accessibility).

HARD GATES (never traded for style): content integrity; legibility at real holding distance in dim venue light; text/background contrast; every price clearly tied to its item; item name, description and price read as one unit.

PROCESS: write a one-sentence creative thesis first and derive the look from it, with an avoid-list; concept precedes decoration; use precedent structurally, never as costume; track hierarchy, typography, colour, concept, craft, originality, restraint and fit separately; a weaker revision should be reverted.

MENU DESIGN: Menu type size must fit actual dining conditions. Menu item name, description and price form a perceptual unit. Price placement preserves item association. Price prominence should reflect the intended decision experience. Menu sections need distinguishable transitions. Descriptions should carry decision-relevant information before decorative prose. Menu descriptions help reduce ordering uncertainty. Menu substrate and finish affect usability. Do not assume universal menu sweet spots. Price-format effects are contextual and limited. Menu gaze behavior varies with audience characteristics. Attention is not equivalent to purchase. Menu visual emphasis should be evaluated separately from sales effect. Menu design dimensions have different behavioral effect sizes. Promoting one menu item can affect substitutes; items compete within categories; combine profitability and observed demand.

TYPOGRAPHY: Typographic roles should map to semantic roles. Type pairing balances similarity and contrast. Typographic contrast has multiple dimensions. Hierarchy needs meaningful difference, not many tiny changes. Tabular figures support numeric alignment; numeric typography should support the comparison task. Typography readability is systemic. Readable measure depends on context. Spacing creates typographic texture. Vertical rhythm connects typographic and layout structure. Type should be designed or adjusted for rendered size (display faces only at display sizes). Uppercase changes texture and reading behavior. Small reverse type requires reproduction care. Expressive typography needs a readability boundary. Text-block darkness participates in composition. Counterform is active form. Optical alignment can differ from geometric alignment. Rag shape affects typographic rhythm. Justification requires spacing control.

COLOUR: Palette roles should be defined, not merely colors. Accent colors gain emphasis through scarcity. Color is contextual; adjacent colors alter perceived appearance; identical colors can appear different on different grounds. Color composition includes value balance. Limited palettes can gain depth through value, overprint and treatment. Do not encode meaning by color alone. Foreground and background require sufficient luminance contrast.

COMPOSITION AND GESTALT: Hierarchy cues should point to the same priority order. Hierarchy requires quiet levels. High contrast is a finite attentional resource. Use simplicity broadly and contrast selectively. Focal dominance is relative. Whitespace must perform relational work. Alignment communicates relationship. Rhythm depends on repetition plus variation. Balance depends on visual weight and distance; asymmetry requires perceptual counterweight. Tangencies and collisions should be deliberate. Density gradients can guide visual flow. Proximity, similarity, enclosure and connectedness group elements and should reinforce each other. Headings and spacing should expose content groups. Grid structure should respond to content structure; a grid is an organizing system, not a visible cage; gutters must clearly separate columns.

ART DIRECTION AND IMAGERY: Semantic purpose should precede formal choice. Appropriateness is contextual, not stylistic. Literal motifs should be budgeted (not agave + cactus + sun + sombrero at once). Abstraction can reduce literal category cliché. A motif should behave as a system, not a stamp. Image and type should have a semantic relationship. Maximalism requires stronger hierarchy, not less; dense compositions benefit from quiet counterfields. Visual surprise should not obstruct the primary task. Image treatment should behave as a system. Cropping changes image meaning and energy. Identity can use multiple reinforcing cues (type, palette, composition, imagery, materiality).`;
