import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"Content-Type":"application/json"}});
const num=(v:any)=>{if(v===null||v===undefined||v==="")return null;const n=Number(String(v).replace(/[$,% ,]/g,""));return Number.isFinite(n)?n:null};
const date=(v:any)=>{if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString().slice(0,10)};
Deno.serve(async req=>{if(req.method!=="POST")return out({error:"POST required"},405);const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return out({error:"config"},500);
const sb=createClient(url,key,{auth:{persistSession:false}}),b=await req.json().catch(()=>({})),importId=b.import_id;if(!importId)return out({error:"import_id required"},400);
const {data:rows,error}=await sb.rpc("phg_sales_validation_rows",{p_import_id:importId});if(error)return out({error:error.message},500);
const aliases:any={business_date:["business_date","date","business date"],revenue_center:["revenue_center","revenue center","center"],item_name:["item_name","item","menu item","product"],category:["category","sales category"],subcategory:["subcategory","sub category"],quantity:["quantity","qty","units"],gross_sales:["gross_sales","gross sales","gross"],discounts:["discounts","discount"],comps:["comps","comp"],refunds:["refunds","refund"],net_sales:["net_sales","net sales","sales","net"],tax:["tax","taxes"],tips:["tips","tip","cc tips"],guest_count:["guest_count","guests","covers"],check_count:["check_count","checks","orders"]};
const pick=(r:any,n:string)=>{const keys=Object.keys(r);for(const a of aliases[n]){const k=keys.find(x=>x.trim().toLowerCase()===a);if(k!==undefined)return r[k]}return null};
let valid=0,warn=0,invalid=0;const updates:any[]=[];for(const row of rows||[]){const raw=row.raw_row||{},issues:any[]=[];const bd=date(pick(raw,"business_date")),net=num(pick(raw,"net_sales"));if(!bd)issues.push({severity:"fail",field:"business_date",message:"Missing or invalid business date"});if(net===null)issues.push({severity:"fail",field:"net_sales",message:"Missing or invalid net sales"});
const n:any={business_date:bd,revenue_center:String(pick(raw,"revenue_center")||"unspecified"),item_name:pick(raw,"item_name"),category:pick(raw,"category"),subcategory:pick(raw,"subcategory"),quantity:num(pick(raw,"quantity"))||0,gross_sales:num(pick(raw,"gross_sales")),discounts:num(pick(raw,"discounts")),comps:num(pick(raw,"comps")),refunds:num(pick(raw,"refunds")),net_sales:net,tax:num(pick(raw,"tax")),tips:num(pick(raw,"tips")),guest_count:num(pick(raw,"guest_count")),check_count:num(pick(raw,"check_count"))};
if(n.gross_sales!==null&&n.net_sales!==null){const expected=n.gross_sales-(n.discounts||0)-(n.comps||0)-(n.refunds||0);if(Math.abs(expected-n.net_sales)>.02)issues.push({severity:"warning",field:"net_sales",message:"Net sales do not reconcile to gross less discounts/comps/refunds",expected,actual:n.net_sales});}
const status=issues.some(x=>x.severity==="fail")?"invalid":issues.length?"warning":"valid";if(status==="invalid")invalid++;else if(status==="warning")warn++;else valid++;updates.push({id:row.id,normalized_row:n,row_status:status,issues});}
const finalStatus=invalid?"fail":warn?"warning":"pass";const {error:ae}=await sb.rpc("phg_sales_validation_apply",{p_import_id:importId,p_updates:updates,p_validation:{validation_type:"row_validation",status:finalStatus,actual:{total:(rows||[]).length,valid,warnings:warn,invalid},notes:"Generic sales normalization and arithmetic reconciliation"}});if(ae)return out({error:ae.message},500);
return out({import_id:importId,total:(rows||[]).length,valid,warnings:warn,invalid,status:finalStatus});});