#!/usr/bin/env python3
"""Convert researcher output (data/mixology/formulation_batch*_*.jsonl) into a reviewable phg_mix migration.

Rules enforced (handoff/PHG_FORMULATION_HANDOFF.txt, .claude/skills/phg-cocktail-formulation):
  - every row needs source.url + quote; rows without them are rejected (listed in the report, never loaded)
  - class/basis/confidence/verification must be valid enum values
  - sugar: sugar_g_100ml is used as given; sugar_g_100g + density -> derived per-100 mL; neither -> NULL
  - a liqueur/sweetener/vermouth with no sugar gets "Resolve ..." in notes (so the coverage view flags it)
  - regulatory bounds go to sugar_profile/variability, never into the point value
  - existing keys are never overwritten (on conflict do nothing); aliases never re-pointed
Usage: python3 scripts/formulation_jsonl_to_sql.py data/mixology/formulation_batch3_*.jsonl > supabase/migrations/<ts>_...sql
"""
import json, re, sys, hashlib

CLASSES = {'sweetener','citrus_juice','fruit_juice','liqueur','spirit','acid_solution','water','carbonated_mixer','other'}
BASES = {'generic','specific_product','reference_solution','literature_range','working_model'}
CONF = {'high','medium','low'}
VERIF = {'official','peer_reviewed','primary_practitioner','secondary','derived'}

def q(v):
    if v is None: return 'null'
    if isinstance(v, bool): return 'true' if v else 'false'
    if isinstance(v, (int, float)): return repr(v)
    return "'" + str(v).replace("'", "''") + "'"

def j(v): return q(json.dumps(v or {}, ensure_ascii=False)) + '::jsonb'

def num(v):
    try: return None if v in (None, '') else float(v)
    except (TypeError, ValueError): return None

def src_key(url):
    host = re.sub(r'^https?://(www\.)?', '', url).split('/')[0]
    base = re.sub(r'[^a-z0-9]+', '_', host.lower()).strip('_')[:40]
    return f"src_{base}_{hashlib.sha1(url.encode()).hexdigest()[:6]}"

rows, rejected = [], []
for path in sys.argv[1:]:
    for n, line in enumerate(open(path, encoding='utf-8'), 1):
        line = line.strip()
        if not line: continue
        try: r = json.loads(line)
        except json.JSONDecodeError as e: rejected.append((path, n, f'bad json: {e}')); continue
        s = r.get('source') or {}
        why = []
        if not re.fullmatch(r'ip_[a-z0-9_]+', r.get('profile_key') or ''): why.append('bad profile_key')
        if not s.get('url'): why.append('no source url')
        if not r.get('quote'): why.append('no quote')
        if r.get('ingredient_class') not in CLASSES: why.append(f"class {r.get('ingredient_class')}")
        if r.get('basis') not in BASES: why.append(f"basis {r.get('basis')}")
        if r.get('confidence') not in CONF: why.append(f"confidence {r.get('confidence')}")
        if r.get('verification') not in VERIF: why.append(f"verification {r.get('verification')}")
        if why: rejected.append((path, n, '; '.join(why) + f" [{r.get('profile_key')}]")); continue
        rows.append(r)

seen = set(); out = []
out.append('-- Generated by scripts/formulation_jsonl_to_sql.py from: ' + ', '.join(sys.argv[1:]))
out.append('-- REVIEW BEFORE APPLYING. Rejected rows are listed at the end as comments.')
for r in rows:
    k = r['profile_key']
    if k in seen: out.append(f'-- duplicate key skipped: {k}'); continue
    seen.add(k)
    s = r['source']; sk = src_key(s['url'])
    out.append(f"insert into phg_mix.sources (key, title, kind, source_kind, tier, publisher, year, url, access, focus) values "
               f"({q(sk)}, {q((s.get('title') or s['url'])[:300])}, {q('publication' if r['verification'] in ('official','peer_reviewed') and not r.get('brand') else 'brand' if r.get('brand') else 'site')}, null, "
               f"{1 if r['verification'] in ('official','peer_reviewed') else 2 if r['verification']=='primary_practitioner' else 3}, {q(s.get('publisher'))}, null, {q(s['url'])}, 'open', '{{formulation}}') on conflict (key) do nothing;")
    dens = num(r.get('density_g_ml')); s100 = num(r.get('sugar_g_100ml')); s100g = num(r.get('sugar_g_100g'))
    derived = s100 is None and s100g is not None and dens is not None
    if derived: s100 = round(s100g * dens, 2)
    notes = (r.get('notes') or '').strip()
    if r['ingredient_class'] in ('liqueur', 'sweetener') and s100 is None and s100g is None and 'resolve' not in notes.lower():
        notes = ('Resolve sugar: not published by an accessible primary source. ' + notes).strip()
    sp = dict(r.get('sugar_profile') or {})
    if r.get('sugar_bound'): sp['bound'] = r['sugar_bound']
    ap = {}
    if r.get('ta_basis'): ap['ta_basis'] = r['ta_basis']
    var = {k2: r[k2] for k2 in ('market', 'abv_market') if r.get(k2)}
    if r.get('density_basis'): var['density_basis'] = r['density_basis']
    mb = f"{s.get('publisher') or ''}: {s.get('locator') or ''} - \"{r['quote'][:400]}\"" + (' Sugar per 100 mL derived = sugar/100 g x density.' if derived else '')
    out.append("insert into phg_mix.ingredient_profiles (key, name, ingredient_class, brand, generic_name, basis, density_g_ml, abv_pct, "
               "sugar_g_100ml, sugar_g_100g, ta_g_100ml, ta_min_g_100ml, ta_max_g_100ml, ph, sugar_profile, acid_profile, variability, "
               "measurement_basis, confidence, verification, notes) values ("
               + ', '.join([q(k), q(r.get('name') or k), q(r['ingredient_class']), q(r.get('brand')), q(r.get('generic_name')), q(r['basis']),
                            q(dens), q(num(r.get('abv_pct'))), q(s100), q(s100g), q(num(r.get('ta_g_100ml'))), q(num(r.get('ta_min'))),
                            q(num(r.get('ta_max'))), q(num(r.get('ph'))), j(sp), j(ap), j(var), q(mb), q(r['confidence']), q(r['verification']),
                            q(notes or None)])
               + ") on conflict (key) do nothing;")
    out.append(f"insert into phg_mix.formulation_evidence (record_type, record_key, source_key, url, locator, evidence_role, note) values "
               f"('ingredient_profile', {q(k)}, {q(sk)}, {q(s['url'])}, {q(s.get('locator'))}, 'primary', {q(r['quote'][:300])}) on conflict do nothing;")
    for a in r.get('aliases') or []:
        a = str(a).strip().lower()
        if a:
            out.append(f"insert into phg_mix.ingredient_profile_aliases (alias, profile_key, alias_type) select {q(a)}, {q(k)}, 'recipe_term' "
                       f"where not exists (select 1 from phg_mix.ingredient_profile_aliases x where lower(x.alias) = {q(a)});")
out.append(f'-- loaded rows: {len(seen)}; rejected: {len(rejected)}')
for p, n, why in rejected: out.append(f'-- REJECTED {p}:{n} {why}')
print('\n'.join(out))
