#!/usr/bin/env python3
"""Generate supabase/migration_drafts/04a_gl_template_bar_restaurant.sql from
data/finance/gl_template_bar_restaurant.csv (chart) and data/finance/invoice_coding_template.json (vendor profiles).
Re-run after editing either file; the SQL is idempotent (on conflict do nothing / do update for template rows)."""
import csv, json
root = __file__.rsplit('/scripts/', 1)[0]
KEY = 'bar_restaurant_standard'
rows = list(csv.DictReader(open(f'{root}/data/finance/gl_template_bar_restaurant.csv')))
tpl = json.load(open(f'{root}/data/finance/invoice_coding_template.json'))
codes = {r['code'] for r in rows}

def q(v):
    return 'null' if v in (None, '') else "'" + str(v).replace("'", "''") + "'"
def arr(xs):
    return "'{}'::text[]" if not xs else 'array[' + ','.join(q(x) for x in xs) + ']::text[]'
def qj(o):
    return q(json.dumps(o, ensure_ascii=False)) + '::jsonb'

for r in rows:
    assert not r['parent_code'] or r['parent_code'] in codes, r['code']
pats = tpl['line_patterns']
profiles = []
for p in tpl['profiles']:
    rules = []
    for i, (pk, gl) in enumerate(p['line_rules']):
        assert gl in codes, (p['key'], gl)
        rules.append({'order': i + 1, 'pattern_key': pk if pk in pats else None,
                      'pattern': pats.get(pk, pk), 'gl_code': gl})
    assert not p['default_gl'] or p['default_gl'] in codes, p['key']
    profiles.append((p, rules))

sort = lambda c: int(c.replace('-', '')) * (1 if '-' in c else 100)
out = []
w = out.append
w(f"""-- DRAFT 04a: NOT APPLIED. Needs Rob's approval. Apply right after draft 04 (needs phg.gl_accounts); 02 is optional
-- (the parties column below is added only if phg.parties exists).
-- GENERATED by scripts/gl_template_sql.py from data/finance/gl_template_bar_restaurant.csv and
-- data/finance/invoice_coding_template.json. Edit those files and re-run; do not hand-edit this file.
--
-- What this does (plain English)
--   Rob 2026-09-29: the Airtable invoices and GL codes are one business's example of how to categorize invoices; build a
--   template from it. So:
--   * phg.gl_accounts gets a shared template '{KEY}' ({len(rows)} accounts, account_id NULL, source 'template'):
--     revenue 4xxx, COGS 5xxx by category (liquor, beer, wine, bar mix, N/A, food), labor 61xx (management / hourly /
--     taxes and benefits), operating supplies 62xx, facility 63xx, G&A 64xx, marketing 65xx, occupancy 70xx and
--     below-the-line 80xx, plus deposits and capital purchases. Numbering follows the example so a business that already
--     uses that style maps 1:1; every row carries a budget group (declining budget) and an expense category
--     (phg.expense_categories key). A business copies the template into its own rows during setup and renames,
--     merges or drops accounts by talking ("we don't split beer and wine").
--   * phg.gl_templates: one row per template with its general coding rules (split by line, deposits, freight,
--     capitalization threshold ...).
--   * phg.gl_coding_profiles: {len(profiles)} vendor profiles (wine & spirits distributor, broadline foodservice, linen
--     service, marketplace / big box ...) with a default GL, when to ask, and ordered line rules (regex on the line
--     description -> GL code). When a new vendor shows up Harmony asks which profile it is, stores it on the party, and
--     copies the rules into phg.invoice_coding_rules (draft 02) for that vendor as source 'inferred', to be confirmed.
--   * phg.parties.coding_profile (nullable) when draft 02 is applied.
--   * The older 14-row 'restaurant_usar' seed in draft 04 is left as is; new businesses start from '{KEY}'.
--   Backtest (scripts/gl_template_backtest.py on the example's 469 invoices): the matched profile can produce 98% of
--   the coded GL lines and 99% of the dollars (parent-level coding counted as covered).
--
-- Rollback (one transaction)
--   begin;
--   set local lock_timeout = '3s';
--   delete from phg.harmony_table_access where schema_name = 'phg' and table_pattern in ('gl_templates','gl_coding_profiles');
--   drop table if exists phg.gl_coding_profiles, phg.gl_templates;
--   alter table if exists phg.parties drop column if exists coding_profile;
--   delete from phg.gl_accounts where account_id is null and template_key = '{KEY}';
--   alter table phg.gl_accounts drop column if exists notes;
--   commit;
--   (Copies a business already made into its own rows are kept; they are that business's chart.)

set local lock_timeout = '3s';

alter table phg.gl_accounts add column if not exists notes text;   -- what belongs in the account (shown when Harmony asks)

create table if not exists phg.gl_templates (
  template_key   text primary key,
  label          text not null,
  description    text not null,
  general_rules  jsonb not null default '[]'::jsonb,   -- [{{key, rule}}]
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists phg.gl_coding_profiles (
  template_key   text not null references phg.gl_templates(template_key) on delete cascade,
  profile_key    text not null,
  label          text not null,
  party_kinds    text[] not null default '{{}}',        -- phg.parties.kinds values this profile usually has
  name_hints     text[] not null default '{{}}',        -- well-known vendor names of this type (recognition only)
  default_gl     text,                                  -- null = never default; code every line
  ask            text not null check (ask in ('no_match','per_line','once','mixed_receipt')),
  split_lines    boolean not null default true,
  line_rules     jsonb not null default '[]'::jsonb,    -- [{{order, pattern_key, pattern (regex, case-insensitive), gl_code}}]
  notes          text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  primary key (template_key, profile_key)
);

do $$ begin
  if to_regclass('phg.parties') is not null then
    execute 'alter table phg.parties add column if not exists coding_profile text';   -- phg.gl_coding_profiles.profile_key
  end if;
end $$;

-- rights: service_role reads and writes; Harmony's reader may read the two catalog tables; nobody else.
-- Explicit grants and policies only (not phg.harmony_apply_table_access(), which touches other tables).
alter table phg.gl_templates enable row level security;
alter table phg.gl_coding_profiles enable row level security;
revoke all on phg.gl_templates, phg.gl_coding_profiles from public, anon, authenticated;
grant select, insert, update, delete on phg.gl_templates, phg.gl_coding_profiles to service_role;
grant select on phg.gl_templates, phg.gl_coding_profiles to phg_harmony_reader;
drop policy if exists harmony_read on phg.gl_templates;
create policy harmony_read on phg.gl_templates for select to phg_harmony_reader using (true);
drop policy if exists harmony_read on phg.gl_coding_profiles;
create policy harmony_read on phg.gl_coding_profiles for select to phg_harmony_reader using (true);
insert into phg.harmony_table_access (schema_name, table_pattern, access, notes) values
  ('phg','gl_templates','shared_read','GL chart templates and their general coding rules (draft 04a)'),
  ('phg','gl_coding_profiles','shared_read','vendor profiles for invoice GL coding (draft 04a)')
on conflict (schema_name, table_pattern) do nothing;

insert into phg.gl_templates (template_key, label, description, general_rules) values
  ({q(KEY)}, 'Bar & restaurant standard', {q(tpl['about'])}, {qj(tpl['general_rules'])})
on conflict (template_key) do update set label = excluded.label, description = excluded.description,
  general_rules = excluded.general_rules, updated_at = now();
""")
w("-- chart of accounts template (account_id NULL). Template rows are refreshed from the CSV; business rows are untouched.")
w("insert into phg.gl_accounts (account_id, template_key, code, name, parent_code, type, cogs_category, labor_class,")
w("                             expense_category_key, budget_group, sort, source, notes) values")
vals = []
for r in rows:
    vals.append(f"  (null,{q(KEY)},{q(r['code'])},{q(r['name'])},{q(r['parent_code'])},{q(r['type'])},{q(r['cogs_category'])},"
                f"{q(r['labor_class'])},{q(r['expense_category_key'])},{q(r['budget_group'])},{sort(r['code'])},'template',{q(r['notes'])})")
w(',\n'.join(vals))
w("""on conflict (coalesce(account_id, '00000000-0000-0000-0000-000000000000'::uuid), template_key, code) do update set
  name = excluded.name, parent_code = excluded.parent_code, type = excluded.type, cogs_category = excluded.cogs_category,
  labor_class = excluded.labor_class, expense_category_key = excluded.expense_category_key,
  budget_group = excluded.budget_group, sort = excluded.sort, notes = excluded.notes, updated_at = now()
  where phg.gl_accounts.account_id is null;
""")
w("insert into phg.gl_coding_profiles (template_key, profile_key, label, party_kinds, name_hints, default_gl, ask, split_lines, line_rules, notes) values")
vals = []
for p, rules in profiles:
    vals.append(f"  ({q(KEY)},{q(p['key'])},{q(p['label'])},{arr(p['party_kinds'])},{arr(p['name_hints'])},{q(p['default_gl'])},"
                f"{q(p['ask'])},{'true' if p['split_lines'] else 'false'},{qj(rules)},{q(p['notes'])})")
w(',\n'.join(vals))
w("""on conflict (template_key, profile_key) do update set label = excluded.label, party_kinds = excluded.party_kinds,
  name_hints = excluded.name_hints, default_gl = excluded.default_gl, ask = excluded.ask, split_lines = excluded.split_lines,
  line_rules = excluded.line_rules, notes = excluded.notes, updated_at = now();
""")
w(f"""-- every profile's codes must exist in the template chart
do $$ declare bad text; begin
  select string_agg(distinct x.code, ', ') into bad from (
    select profile_key, default_gl code from phg.gl_coding_profiles where template_key = {q(KEY)} and default_gl is not null
    union all
    select profile_key, r->>'gl_code' from phg.gl_coding_profiles, jsonb_array_elements(line_rules) r where template_key = {q(KEY)}
  ) x where not exists (select 1 from phg.gl_accounts g where g.account_id is null and g.template_key = {q(KEY)} and g.code = x.code);
  if bad is not null then raise exception '04a: profile codes missing from the chart: %', bad; end if;
end $$;
""")
open(f'{root}/supabase/migration_drafts/04a_gl_template_bar_restaurant.sql', 'w').write('\n'.join(out))
print(len(rows), 'accounts,', len(profiles), 'profiles')
