#!/usr/bin/env python3
"""Build idempotent SQL that loads data/mixology/*.jsonl into phg_mix, with credibility and quality scores.

Rules: handoff/agents/MIXOLOGY_DATA_CONTRACT.md (format) and handoff/agents/MIXOLOGY_CREDIBILITY_SCORING.md (scores).
Usage: python3 scripts/mixology_load.py [files...] > load.sql   (default: every data/mixology/*.jsonl)
Scores are recomputed on every run; nothing in the DB is hand-edited. Until a scoring batch supplies evidenced
credibility parts, a source's/creator's credibility is PROVISIONAL, from its tier (cred_parts.provisional = true).
"""
import glob, json, re, sys

TIER_BASE = {1: 82, 2: 72, 3: 62, 4: 48, 5: 22}
KINDS = {"canon_author", "pro_bartender", "bar", "publication", "reference_site", "technical_creator",
         "lifestyle_influencer", "brand", "academic", "historian"}
PREP_CATS = {"syrup", "rich_syrup", "flavored_syrup", "cordial", "infusion", "shrub", "oleo", "tincture", "bitters",
             "fat_wash", "milk_punch", "clarified_juice", "acid_blend", "super_juice", "foam", "gel", "air", "caviar",
             "brine", "salt_solution", "other"}
TECH_CATS = {"classic", "dilution", "clarification", "infusion", "carbonation", "temperature", "texture",
             "spherification", "fermentation", "acid_adjustment", "distillation", "aroma", "ice", "balance"}
METHODS = {"shake", "stir", "build", "throw", "swizzle", "blend", "dry_shake", "whip", "clarified", "carbonated", "layer", "other"}
ERAS = {"pre-prohibition", "prohibition", "tiki", "post-war", "disco", "modern_classic", "contemporary"}
FAMILIES = {"old_fashioned", "martini", "daiquiri", "sidecar", "highball", "flip", "other"}


def q(v):
    """SQL literal."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, (dict, list)) and not (isinstance(v, list) and all(isinstance(x, str) for x in v)):
        return "'" + json.dumps(v, ensure_ascii=False).replace("'", "''") + "'::jsonb"
    if isinstance(v, list):
        return "array[" + ",".join(q(x) for x in v) + "]::text[]" if v else "'{}'::text[]"
    return "'" + str(v).replace("'", "''") + "'"


def qj(v):
    """jsonb literal (always jsonb, even for an empty list)."""
    return "null" if v is None else "'" + json.dumps(v, ensure_ascii=False).replace("'", "''") + "'::jsonb"


def num(v):
    try:
        return float(v) if v is not None and str(v).strip() != "" else None
    except (TypeError, ValueError):
        return None


def grade(s):
    return "A" if s >= 85 else "B" if s >= 70 else "C" if s >= 50 else "D" if s >= 30 else "E"


def load(files):
    recs = {}
    for f in files:
        for line in open(f):
            if not line.strip():
                continue
            o = json.loads(line)
            k = (o["type"], o["key"])
            if k in recs:  # merge: keep the fuller record, union the sources
                old = recs[k]
                srcs = {(s.get("source_key"), s.get("url")): s for s in old.get("sources", []) + o.get("sources", [])}
                if len(json.dumps(o)) > len(json.dumps(old)):
                    old = o
                old["sources"] = list(srcs.values())
                recs[k] = old
            else:
                recs[k] = o
    return recs


def main():
    files = sys.argv[1:] or sorted(glob.glob("data/mixology/*.jsonl"))
    recs = load(files)
    by = lambda t: [o for (tt, _), o in recs.items() if tt == t]
    sources, creators = by("source"), by("creator")
    src_keys = {s["key"] for s in sources}
    cred = {}
    out = ["-- generated by scripts/mixology_load.py from: " + ", ".join(files), "set local lock_timeout = '3s';"]
    warn = []

    for s in sources:
        tier = int(s.get("tier") or 4)
        score = TIER_BASE.get(tier, 40)
        cred[s["key"]] = score
        kind = s.get("source_kind") if s.get("source_kind") in KINDS else None
        out.append(
            "insert into phg_mix.sources (key,title,kind,source_kind,tier,authors,publisher,year,url,platforms,focus,notable_for,access,rights_note,recipe_count_estimate,reach,cred_score,cred_grade,cred_parts) values ("
            + ",".join([q(s["key"]), q(s.get("title") or s["key"]), q(s.get("kind") or "site"), q(kind), str(tier), q(s.get("authors") or []),
                        q(s.get("publisher")), q(s.get("year") if isinstance(s.get("year"), int) else None), q(s.get("url")), qj(s.get("platforms") or []),
                        q(s.get("focus") or []), q(s.get("notable_for")),
                        q(s.get("access") if s.get("access") in ("open", "paywalled", "print_only", "login") else None), q(s.get("rights_note")),
                        q(s.get("recipe_count_estimate") if isinstance(s.get("recipe_count_estimate"), int) else None), qj(s.get("reach") or {}),
                        str(score), q(grade(score)), qj({"provisional": True, "basis": f"tier {tier}"})])
            + ") on conflict (key) do update set title=excluded.title, kind=excluded.kind, source_kind=coalesce(excluded.source_kind, phg_mix.sources.source_kind), tier=excluded.tier, authors=excluded.authors, publisher=excluded.publisher, year=excluded.year, url=excluded.url, platforms=excluded.platforms, focus=excluded.focus, notable_for=excluded.notable_for, access=excluded.access, rights_note=excluded.rights_note, recipe_count_estimate=excluded.recipe_count_estimate, cred_score=excluded.cred_score, cred_grade=excluded.cred_grade, cred_parts=excluded.cred_parts, updated_at=now();")

    for c in creators:
        tier = c.get("tier") if isinstance(c.get("tier"), int) else None
        score = TIER_BASE.get(tier or 3, 40)
        cred[c["key"]] = score
        role = c.get("role") if c.get("role") in ("bartender", "author", "creator", "scientist", "chef", "historian", "owner") else None
        kind = c.get("creator_kind") if c.get("creator_kind") in KINDS else None
        out.append(
            "insert into phg_mix.creators (key,name,role,creator_kind,tier,affiliations,home_url,platforms,known_for,signature_drinks,techniques,cred_score,cred_grade,cred_parts) values ("
            + ",".join([q(c["key"]), q(c.get("name") or c["key"]), q(role), q(kind), q(tier), q(c.get("affiliations") or []), q(c.get("home_url")),
                        qj(c.get("platforms") or []), q(c.get("known_for") or []), q(c.get("signature_drinks") or []), q(c.get("techniques") or []),
                        str(score), q(grade(score)), qj({"provisional": True, "basis": f"tier {tier or 'unknown (3)'}"})])
            + ") on conflict (key) do update set name=excluded.name, role=excluded.role, creator_kind=coalesce(excluded.creator_kind, phg_mix.creators.creator_kind), tier=excluded.tier, affiliations=excluded.affiliations, home_url=excluded.home_url, platforms=excluded.platforms, known_for=excluded.known_for, signature_drinks=excluded.signature_drinks, techniques=excluded.techniques, cred_score=excluded.cred_score, cred_grade=excluded.cred_grade, cred_parts=excluded.cred_parts, updated_at=now();")

    def attrib(rtype, o):
        rows, backers = [], []
        for s in o.get("sources") or []:
            sk = s.get("source_key")
            if sk not in src_keys:
                warn.append(f"{o['key']}: unknown source {sk}")
                continue
            backers.append(sk)
            rows.append(f"insert into phg_mix.attributions (record_type,record_key,source_key,url,locator,tier) values ({q(rtype)},{q(o['key'])},{q(sk)},{q(s.get('url'))},{q(s.get('locator'))},{q(s.get('tier') if isinstance(s.get('tier'), int) else None)}) on conflict do nothing;")
        return rows, backers

    def quality(o, backers, completeness):
        best = max((cred.get(b, 0) for b in backers), default=0)
        n = len(set(backers))
        agree = 0 if n == 0 else 8 if n == 1 else 16 if n == 2 else 21 if n == 3 else 25
        locs = " ".join(str(s.get("locator") or "") for s in o.get("sources") or []).lower()
        ver = "page_verified" if "verified on page" in locs else "excerpt" if ("search" in locs or "excerpt" in locs or "summary" in locs) else "unverified"
        # batches produced without page access are excerpt-level even when the locator does not say so
        if ver == "unverified" and backers:
            ver = "excerpt"
        vpts = {"page_verified": 10, "excerpt": 3, "unverified": 0}[ver]
        score = round(0.5 * best + agree + completeness + vpts)
        parts = {"best_backer": best, "agreement": agree, "sources": n, "completeness": completeness, "verification": vpts}
        return max(0, min(100, score)), parts, ver

    for p in by("prep"):
        cat = p.get("category") if p.get("category") in PREP_CATS else "other"
        rows, backers = attrib("prep", p)
        lines = p.get("lines") or []
        comp = (6 if lines and all(num(l.get("amount")) is not None for l in lines) else 0) + (5 if p.get("process") else 0) + (2 if p.get("params") else 0) + (2 if p.get("shelf_life_days") is not None or p.get("storage") else 0)
        score, parts, ver = quality(p, backers, comp)
        out.append(
            "insert into phg_mix.preps (key,name,category,yield,ratio_note,process,params,equipment,shelf_life_days,storage_note,confidence,verification,quality_score,quality_grade,quality_parts) values ("
            + ",".join([q(p["key"]), q(p.get("name") or p["key"]), q(cat), qj(p.get("yield")), q(p.get("ratio_note")), q([str(x) for x in (p.get("process") or [])]),
                        qj(p.get("params") or {}), q([str(x) for x in (p.get("equipment") or [])]), q(num(p.get("shelf_life_days"))), q(p.get("storage")),
                        q(p.get("confidence") if p.get("confidence") in ("high", "medium", "low") else "low"), q(ver), str(score), q(grade(score)), qj(parts)])
            + ") on conflict (key) do update set name=excluded.name, category=excluded.category, yield=excluded.yield, ratio_note=excluded.ratio_note, process=excluded.process, params=excluded.params, equipment=excluded.equipment, shelf_life_days=excluded.shelf_life_days, storage_note=excluded.storage_note, confidence=excluded.confidence, verification=excluded.verification, quality_score=excluded.quality_score, quality_grade=excluded.quality_grade, quality_parts=excluded.quality_parts, updated_at=now();")
        out.append(f"delete from phg_mix.prep_lines where prep_key = {q(p['key'])};")
        for i, l in enumerate(lines):
            out.append(f"insert into phg_mix.prep_lines (prep_key,position,ingredient,amount,unit,note) values ({q(p['key'])},{i + 1},{q(l.get('ingredient') or '?')},{q(num(l.get('amount')))},{q(l.get('unit'))},{q(l.get('note'))});")
        out += rows
        for r in p.get("used_in") or []:
            out.append(f"insert into phg_mix.uses values ('recipe',{q(r)},'prep',{q(p['key'])}) on conflict do nothing;")

    for r in by("recipe"):
        rows, backers = attrib("recipe", r)
        lines = r.get("lines") or []
        comp = (6 if lines and all(num(l.get("amount")) is not None or l.get("unit") in ("dash", "dashes", "top", "rinse", "barspoon") for l in lines) else 0) \
            + (3 if r.get("method") else 0) + (2 if r.get("glass") else 0) + (2 if r.get("garnish") else 0) + (2 if r.get("origin_bar") or r.get("creator_key") or r.get("year_created") else 0)
        score, parts, ver = quality(r, backers, comp)
        fam = r.get("family") if r.get("family") in FAMILIES else "other"
        out.append(
            "insert into phg_mix.recipes (key,name,aka,family,subfamily,style_tags,base_spirits,era,year_created,creator_key,origin_bar,origin_city,method,steps,dilution_target_pct,glass,ice,garnish,abv_est,notes,confidence,verification,quality_score,quality_grade,quality_parts) values ("
            + ",".join([q(r["key"]), q(r.get("name") or r["key"]), q(r.get("aka") or []), q(fam), q(r.get("subfamily")), q(r.get("style_tags") or []), q(r.get("base_spirits") or []),
                        q(r.get("era") if r.get("era") in ERAS else None), q(r.get("year_created") if isinstance(r.get("year_created"), int) else None), q(r.get("creator_key")),
                        q(r.get("origin_bar")), q(r.get("origin_city")), q(r.get("method") if r.get("method") in METHODS else ("other" if r.get("method") else None)),
                        q([str(x) for x in (r.get("steps") or [])]), q(num(r.get("dilution_target_pct"))), q(r.get("glass")), q(r.get("ice")), q(r.get("garnish")),
                        q(num(r.get("abv_est"))), q(r.get("notes")), q(r.get("confidence") if r.get("confidence") in ("high", "medium", "low") else "low"),
                        q(ver), str(score), q(grade(score)), qj(parts)])
            + ") on conflict (key) do update set name=excluded.name, aka=excluded.aka, family=excluded.family, subfamily=excluded.subfamily, style_tags=excluded.style_tags, base_spirits=excluded.base_spirits, era=excluded.era, year_created=excluded.year_created, creator_key=excluded.creator_key, origin_bar=excluded.origin_bar, origin_city=excluded.origin_city, method=excluded.method, steps=excluded.steps, dilution_target_pct=excluded.dilution_target_pct, glass=excluded.glass, ice=excluded.ice, garnish=excluded.garnish, abv_est=excluded.abv_est, notes=excluded.notes, confidence=excluded.confidence, verification=excluded.verification, quality_score=excluded.quality_score, quality_grade=excluded.quality_grade, quality_parts=excluded.quality_parts, updated_at=now();")
        out.append(f"delete from phg_mix.recipe_lines where recipe_key = {q(r['key'])};")
        for i, l in enumerate(lines):
            out.append(f"insert into phg_mix.recipe_lines (recipe_key,position,ingredient,amount,unit,ml,prep_key,note) values ({q(r['key'])},{i + 1},{q(l.get('ingredient') or '?')},{q(num(l.get('amount')))},{q(l.get('unit'))},{q(num(l.get('ml')))},{q(l.get('prep_key'))},{q(l.get('note'))});")
            if l.get("prep_key"):
                out.append(f"insert into phg_mix.uses values ('recipe',{q(r['key'])},'prep',{q(l['prep_key'])}) on conflict do nothing;")
        for v in r.get("variants") or []:
            sk = v.get("source_key") if v.get("source_key") in src_keys else None
            out.append(f"insert into phg_mix.recipe_variants (recipe_key,name,change,source_key,tier,url) values ({q(r['key'])},{q(v.get('name') or 'variant')},{q(v.get('change'))},{q(sk)},{q(v.get('tier') if isinstance(v.get('tier'), int) else None)},{q(v.get('url'))}) on conflict do nothing;")
        out += rows

    for t in by("technique"):
        rows, backers = attrib("technique", t)
        comp = (5 if t.get("steps") else 0) + (4 if t.get("params") else 0) + (3 if t.get("equipment") else 0) + (3 if t.get("safety") or t.get("pitfalls") else 0)
        score, parts, ver = quality(t, backers, comp)
        out.append(
            "insert into phg_mix.techniques (key,name,category,what_it_does,when_to_use,steps,params,equipment,safety,pitfalls,confidence,verification,quality_score,quality_grade,quality_parts) values ("
            + ",".join([q(t["key"]), q(t.get("name") or t["key"]), q(t.get("category") if t.get("category") in TECH_CATS else "classic"), q(t.get("what_it_does")), q(t.get("when_to_use")),
                        q([str(x) for x in (t.get("steps") or [])]), qj(t.get("params") or {}), q([str(x) for x in (t.get("equipment") or [])]),
                        q([str(x) for x in (t.get("safety") or [])]), q([str(x) for x in (t.get("pitfalls") or [])]),
                        q(t.get("confidence") if t.get("confidence") in ("high", "medium", "low") else "low"), q(ver), str(score), q(grade(score)), qj(parts)])
            + ") on conflict (key) do update set name=excluded.name, category=excluded.category, what_it_does=excluded.what_it_does, when_to_use=excluded.when_to_use, steps=excluded.steps, params=excluded.params, equipment=excluded.equipment, safety=excluded.safety, pitfalls=excluded.pitfalls, confidence=excluded.confidence, verification=excluded.verification, quality_score=excluded.quality_score, quality_grade=excluded.quality_grade, quality_parts=excluded.quality_parts, updated_at=now();")
        out += rows
        for r in t.get("example_recipes") or []:
            out.append(f"insert into phg_mix.uses values ('technique',{q(t['key'])},'recipe',{q(r)}) on conflict do nothing;")

    for p in by("pairing"):
        rows, backers = attrib("pairing", p)
        score, parts, ver = quality(p, backers, 10 if p.get("rationale") else 5)
        rel = p.get("relationship") if p.get("relationship") in ("classic_pairing", "complementary", "contrasting", "bridge", "shared_compounds", "regional_tradition") else "complementary"
        out.append(f"insert into phg_mix.pairings (key,relationship,context,rationale,confidence,verification,quality_score,quality_grade) values ({q(p['key'])},{q(rel)},{qj(p.get('context') or {})},{q(p.get('rationale'))},{q(p.get('confidence') if p.get('confidence') in ('high','medium','low') else 'low')},{q(ver)},{score},{q(grade(score))}) on conflict (key) do update set relationship=excluded.relationship, context=excluded.context, rationale=excluded.rationale, confidence=excluded.confidence, verification=excluded.verification, quality_score=excluded.quality_score, quality_grade=excluded.quality_grade;")
        for m in p.get("members") or []:
            out.append(f"insert into phg_mix.pairing_members (pairing_key,subject,kind) values ({q(p['key'])},{q(m.get('subject'))},{q(m.get('kind') or 'ingredient')}) on conflict do nothing;")
        out += rows

    print("\n".join(out))
    for w in warn:
        print("WARN", w, file=sys.stderr)


if __name__ == "__main__":
    main()
