import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"Content-Type":"application/json"}});
Deno.serve(async(req)=>{if(req.method!=="POST")return out({error:"POST required"},405);const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return out({error:"config"},500);
const sb=createClient(url,key,{auth:{persistSession:false}}),b=await req.json().catch(()=>({}));const {data:tests}=await sb.rpc("phg_composition_tests");const selected=(tests||[]).filter((t:any)=>!b.test_key||t.test_key===b.test_key);const rs:any[]=[];
for(const t of selected){try{const r=await fetch(`${url}/functions/v1/phg-capability-router`,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${key}`,"apikey":key},body:JSON.stringify({message:t.user_request})});const d=await r.json();const calls=d.route?.calls||[];const caps=calls.map((x:any)=>x.capability);let pass=r.ok;const reasons:string[]=[];
for(const e of t.expected_capabilities||[])if(!caps.includes(e)&&!d.route?.needs_clarification){pass=false;reasons.push(`missing expected capability: ${e}`);}
for(const f of t.forbidden_capabilities||[])if(caps.includes(f)){pass=false;reasons.push(`forbidden capability used: ${f}`);}
if(!d.route?.needs_clarification&&(calls.length<t.min_calls||(t.max_calls!=null&&calls.length>t.max_calls))){pass=false;reasons.push(`call count ${calls.length} outside expected range`);}
const eb=t.expected_behavior||{};if(eb.must_clarify_best&&!d.route?.needs_clarification){pass=false;reasons.push("undefined best was not clarified");}if(eb.must_clarify_expensive&&!d.route?.needs_clarification){pass=false;reasons.push("undefined expensive was not clarified");}
if(eb.must_use_minimal_tools&&calls.length!==1&&!d.route?.needs_clarification){pass=false;reasons.push("did not use minimal tool count");}
const ev={pass,reasons,capabilities:caps,needs_clarification:!!d.route?.needs_clarification,call_count:calls.length};await sb.rpc("phg_record_composition_test",{p_test_id:t.id,p_status:pass?"passed":"failed",p_route:d.route||null,p_results:d.results||null,p_evaluation:ev,p_error:r.ok?null:JSON.stringify(d)});rs.push({test_key:t.test_key,status:pass?"passed":"failed",evaluation:ev});}catch(e){const ev={pass:false,reasons:[String(e)]};await sb.rpc("phg_record_composition_test",{p_test_id:t.id,p_status:"error",p_route:null,p_results:null,p_evaluation:ev,p_error:String(e)});rs.push({test_key:t.test_key,status:"error",evaluation:ev});}}
return out({total:rs.length,passed:rs.filter(x=>x.status==="passed").length,failed:rs.filter(x=>x.status==="failed").length,errors:rs.filter(x=>x.status==="error").length,results:rs});});