-- PHG formulation profiles, batch 1 (2026-09-30, Rob approved step 1 "sourced profiles").
-- Follows handoff/PHG_FORMULATION_HANDOFF.txt and .claude/skills/phg-cocktail-formulation.
-- Rules: every value has a source + basis + confidence + verification; regulatory limits are stored as bounds;
-- unknown stays NULL; generic terms never inherit a brand's numbers (brand-named recipe lines may map DOWN to the
-- generic profile, which leaves brand ABV unresolved). ABV of generic spirits is deliberately NULL (product-specific).
-- Word "resolve" in notes = mapped_needs_composition in v_recipe_balance_inputs (existing view logic).

-- ---------------------------------------------------------------- sources
insert into phg_mix.sources (key, title, kind, source_kind, tier, publisher, year, url, access, focus) values
 ('src_ttb_27cfr_5_142', '27 CFR 5.142 - Neutral spirits or alcohol (vodka standard of identity)', 'publication', 'publication', 1,
  'U.S. TTB / eCFR', 2026, 'https://www.ecfr.gov/current/title-27/chapter-I/subchapter-A/part-5/subpart-I/section-5.142', 'open', '{spirit composition,regulation,vodka}'),
 ('src_ttb_27cfr_5_143', '27 CFR 5.143 - Whisky (types and permitted coloring/flavoring/blending materials)', 'publication', 'publication', 1,
  'U.S. TTB / eCFR', 2026, 'https://www.ecfr.gov/current/title-27/chapter-I/subchapter-A/part-5/subpart-I/section-5.143', 'open', '{spirit composition,regulation,whisky}'),
 ('src_eu_2019_787', 'Regulation (EU) 2019/787 on spirit drinks - Annex I (22) London gin', 'publication', 'publication', 1,
  'European Parliament and Council (via legislation.gov.uk)', 2019, 'https://www.legislation.gov.uk/eur/2019/787/annex/I/division/22/adopted', 'open', '{spirit composition,regulation,gin}'),
 ('src_nom_006_tequila', 'NOM-006-SCFI-2012 Alcoholic beverages - Tequila - Specifications (English)', 'publication', 'publication', 1,
  'Consejo Regulador del Tequila (CRT)', 2012, 'https://www.crt.org.mx/wp-content/uploads/2024/01/NOM-006-SCFI-2012%20-%20INGLES.pdf', 'open', '{spirit composition,regulation,tequila}'),
 ('src_usda_fdc_sr_legacy', 'USDA FoodData Central - SR Legacy', 'database', 'academic', 1,
  'USDA Agricultural Research Service', 2019, 'https://fdc.nal.usda.gov/', 'open', '{food composition,sugars,juices}'),
 ('src_brix_sg_table', 'Degrees Brix to Specific Gravity Conversion Tables (apparent SG 20/20 C)', 'database', 'reference_site', 3,
  'Chemical Tanker Knowledge Base', 2020, 'https://chemicaltankerknowledgebase.com/wp-content/uploads/2020/08/Degrees-Brix-to-SG-Tables.pdf', 'open', '{Brix,density,sucrose}'),
 ('src_coca_cola_us_nutrition', 'Coca-Cola Original - Nutrition Facts (US)', 'brand', 'brand', 1,
  'The Coca-Cola Company', 2026, 'https://www.coca-cola.com/us/en/brands/coca-cola/products/original', 'open', '{mixer composition,sugar}'),
 ('src_state_liquor_listings', 'State liquor authority product listings (Virginia ABC, Ohio OHLQ)', 'database', 'reference_site', 2,
  'Virginia ABC; Ohio Division of Liquor Control', 2026, 'https://www.abc.virginia.gov/products/cordials/angostura-bitters', 'open', '{ABV,product listings}'),
 ('src_haymans_official', 'Hayman''s London Dry Gin - product page', 'brand', 'brand', 1,
  'Hayman''s Gin', 2026, 'https://www.haymansgin.com/product/london-dry-gin/', 'open', '{ABV,gin}')
on conflict (key) do nothing;

-- ---------------------------------------------------------------- existing profiles: add density / sugar
-- Syrup densities: apparent SG 20/20 C (src_brix_sg_table) x 0.998203 g/mL (water at 20 C); sugar/100 mL = Brix x density.
update phg_mix.ingredient_profiles set density_g_ml = 1.2298, sugar_g_100ml = 61.49, updated_at = now(),
  measurement_basis = measurement_basis || ' Density 1.2298 g/mL = SG 1.23202 (50 Brix, 20/20 C) x 0.998203; sugar 61.49 g/100 mL = 50 x 1.2298 (derived).'
 where key = 'ip_simple_1_1_weight' and density_g_ml is null;
update phg_mix.ingredient_profiles set density_g_ml = 1.3269, sugar_g_100ml = 88.46, updated_at = now(),
  measurement_basis = measurement_basis || ' Density 1.3269 g/mL interpolated from SG 1.32820 (66.5) / 1.33007 (66.8 Brix), 20/20 C x 0.998203; sugar 88.46 g/100 mL (derived).'
 where key = 'ip_rich_2_1_weight' and density_g_ml is null;
update phg_mix.ingredient_profiles set density_g_ml = 1.2189, sugar_g_100ml = 58.51, updated_at = now(),
  measurement_basis = measurement_basis || ' Density 1.2189 g/mL = SG 1.22106 (48 Brix, 20/20 C) x 0.998203; sugar 58.51 g/100 mL derived from the ~48 Brix working value (inherits its uncertainty).'
 where key = 'ip_simple_1_1_volume' and density_g_ml is null;
update phg_mix.ingredient_profiles set density_g_ml = 1.3173, sugar_g_100ml = 85.76, updated_at = now(),
  measurement_basis = measurement_basis || ' Density 1.3173 g/mL interpolated from SG 1.31905 (65.0) / 1.32089 (65.3 Brix), 20/20 C x 0.998203; sugar 85.76 g/100 mL derived from the ~65.1 Brix working value.'
 where key = 'ip_rich_2_1_volume' and density_g_ml is null;

-- Citrus: USDA sugars (per 100 g). Density not yet sourced -> sugar_g_100ml stays NULL until it is.
update phg_mix.ingredient_profiles set sugar_g_100g = 2.52, updated_at = now(),
  sugar_profile = sugar_profile || '{"total_g_100g":2.52,"fructose_g_100g":1.10,"glucose_g_100g":0.99,"sucrose_g_100g":0.43,"source":"USDA FDC 167747 Lemon juice, raw"}'::jsonb
 where key = 'ip_lemon_juice_working' and sugar_g_100g is null;
update phg_mix.ingredient_profiles set sugar_g_100g = 1.69, updated_at = now(),
  sugar_profile = sugar_profile || '{"total_g_100g":1.69,"fructose_g_100g":0.61,"glucose_g_100g":0.60,"sucrose_g_100g":0.48,"source":"USDA FDC 168156 Lime juice, raw"}'::jsonb
 where key = 'ip_lime_juice_working' and sugar_g_100g is null;

-- ---------------------------------------------------------------- new profiles
insert into phg_mix.ingredient_profiles
 (key, name, ingredient_class, brand, generic_name, basis, density_g_ml, abv_pct, brix_deg, brix_min, brix_max, brix_type,
  sugar_g_100ml, sugar_g_100g, ta_g_100ml, ta_min_g_100ml, ta_max_g_100ml, sugar_profile, acid_profile, variability,
  measurement_basis, confidence, verification, notes) values
-- syrups with a stated ratio but unstated weight/volume basis: bounded working models
 ('ip_simple_1_1_basis_unspecified', '1:1 Simple Syrup - Weight/Volume Basis Unstated', 'sweetener', null, 'simple syrup', 'working_model',
  1.2243, 0, 49, 48, 50, 'estimated_soluble_solids', 60.0, null, null, null, null,
  '{"primary_sugar":"sucrose","sugar_g_100ml_min":58.51,"sugar_g_100ml_max":61.49}', '{}',
  '{"range_reason":"recipe states 1:1 but not by weight (50 Brix) or by volume (~48 Brix)","relative_error_pct":2.5}',
  'Midpoint of ip_simple_1_1_volume (58.51) and ip_simple_1_1_weight (61.49) g sugar/100 mL.', 'medium', 'derived',
  'Ratio is stated (1:1); only the weight/volume basis is not. Report the 58.5-61.5 g/100 mL range when it matters.'),
 ('ip_rich_2_1_basis_unspecified', '2:1 Rich Syrup - Weight/Volume Basis Unstated', 'sweetener', null, 'rich simple syrup', 'working_model',
  1.3221, 0, 65.9, 65.1, 66.6667, 'estimated_soluble_solids', 87.1, null, null, null, null,
  '{"primary_sugar":"sucrose","sugar_g_100ml_min":85.76,"sugar_g_100ml_max":88.46}', '{}',
  '{"range_reason":"recipe states 2:1 but not by weight (66.7 Brix) or by volume (~65.1 Brix)","relative_error_pct":1.6}',
  'Midpoint of ip_rich_2_1_volume (85.76) and ip_rich_2_1_weight (88.46) g sugar/100 mL.', 'medium', 'derived',
  'Ratio is stated (2:1); only the weight/volume basis is not. Report the 85.8-88.5 g/100 mL range when it matters.'),
-- generic spirits (ABV deliberately NULL: product-specific)
 ('ip_vodka_generic', 'Vodka - Product Unspecified (US standard)', 'spirit', null, 'vodka', 'generic',
  null, null, null, null, null, 'not_applicable', 0, null, 0, 0, 0.1,
  '{"us_max_sugar_g_l":2}', '{"us_max_citric_acid_g_l":1}', '{"abv":"product-specific; needed for ABV math"}',
  'US vodka may be treated with up to 2 g/L sugar and 1 g/L citric acid (27 CFR 5.142); modeled as 0 (max 0.2 g sugar and 0.1 g acid per 100 mL).',
  'high', 'official', 'Sugar/acid are regulatory bounds, not measurements. ABV unknown until the product is named.'),
 ('ip_london_dry_gin_generic', 'London (Dry) Gin - Product Unspecified', 'spirit', null, 'london dry gin', 'generic',
  null, null, null, null, null, 'not_applicable', 0, null, 0, null, null,
  '{"eu_max_sweetening_g_l":0.1}', '{}', '{"eu_min_abv_pct":37.5,"abv":"product-specific"}',
  'EU 2019/787 Annex I(22): London gin not sweetened above 0.1 g/L (as invert sugar), not coloured, min 37.5% ABV.',
  'high', 'official', 'Sugar modeled as 0 (legal max 0.01 g/100 mL). ABV unknown until the product is named.'),
 ('ip_gin_generic', 'Gin - Style/Product Unspecified (dry style assumed)', 'spirit', null, 'gin', 'working_model',
  null, null, null, null, null, 'not_applicable', 0, null, 0, null, null,
  '{}', '{}', '{"exceptions":"Old Tom and other sweetened gins carry sugar - map them to their own profile","abv":"product-specific"}',
  'PHG working model: an unqualified "gin" in a recipe is a dry (unsweetened) gin. Not a regulatory limit outside London gin.',
  'medium', 'derived', 'Working model, not a measurement. Old Tom gin is NOT mapped here. ABV unknown until the product is named.'),
 ('ip_bourbon_generic', 'Bourbon Whiskey - Product Unspecified', 'spirit', null, 'bourbon', 'generic',
  null, null, null, null, null, 'not_applicable', 0, null, 0, null, null,
  '{}', '{}', '{"abv":"product-specific (bottled-in-bond 50%, cask strength higher)"}',
  '27 CFR 5.143 table 1: bourbon whisky may not contain coloring, flavoring or blending materials ("Yes, except for bourbon whisky"); straight bourbon likewise "No".',
  'high', 'official', 'No added sugar by law; barrel-derived acids/solids are small and not modeled. ABV unknown until the product is named.'),
 ('ip_straight_rye_generic', 'Straight Rye Whiskey - Product Unspecified', 'spirit', null, 'straight rye whiskey', 'generic',
  null, null, null, null, null, 'not_applicable', 0, null, 0, null, null,
  '{}', '{}', '{"abv":"product-specific"}',
  '27 CFR 5.143 table 1 type (5): straight rye whisky - coloring, flavoring, blending materials NOT permitted.',
  'high', 'official', 'No added sugar by law. ABV unknown until the product is named.'),
 ('ip_rye_whiskey_generic', 'Rye Whiskey - Product Unspecified', 'spirit', null, 'rye whiskey', 'working_model',
  null, null, null, null, null, 'not_applicable', 0, null, 0, null, null,
  '{}', '{}', '{"note":"non-straight rye may legally contain blending materials (27 CFR 5.143 type 2)","abv":"product-specific"}',
  'PHG working model: sugar ~0. Unlike bourbon, non-straight rye whisky may contain harmless blending materials (27 CFR 5.143 type 2).',
  'medium', 'derived', 'Working model. Use ip_straight_rye_generic when the recipe says straight rye. ABV unknown until the product is named.'),
 ('ip_bourbon_or_rye_generic', 'Bourbon or Rye Whiskey - Recipe Leaves Choice Open', 'spirit', null, 'american whiskey', 'working_model',
  null, null, null, null, null, 'not_applicable', 0, null, 0, null, null,
  '{}', '{}', '{"abv":"product-specific"}',
  'Bourbon (no additives, 27 CFR 5.143) or rye (sugar ~0 working model); sugar/acid modeled as 0 either way.',
  'medium', 'derived', 'Working model for "bourbon or rye" lines. ABV unknown until the product is named.'),
 ('ip_tequila_generic', 'Tequila - Product Unspecified (NOM-006)', 'spirit', null, 'tequila', 'working_model',
  null, null, null, null, null, 'not_applicable', 0, null, 0, null, null,
  '{"abocado_additives_max_pct_by_weight":1,"abocado_may_include":["caramel coloring","oak extract","glycerin","sugar-based syrup"]}', '{}',
  '{"abv":"product-specific","sugar_upper_bound_g_100g":1}',
  'NOM-006-SCFI-2012 s.4.1: mellowing (abocado) additives, which may include sugar-based syrup, must not exceed 1% of total tequila weight before bottling. Modeled as 0 sugar (upper bound ~1 g/100 g).',
  'medium', 'derived', 'Working model within a regulatory bound; additive use is not disclosed on labels. ABV unknown until the product is named.'),
-- branded products (ABV from label/listing)
 ('ip_ketel_one_vodka', 'Ketel One Vodka', 'spirit', 'Ketel One', 'vodka', 'specific_product',
  null, 40, null, null, null, 'not_applicable', 0, null, 0, 0, 0.1,
  '{"us_max_sugar_g_l":2}', '{"us_max_citric_acid_g_l":1}', '{}',
  'ABV 40% (80 proof) per US state liquor listings; sugar/acid bounded by the US vodka standard (27 CFR 5.142).',
  'high', 'secondary', 'ABV from product listings; sugar/acid are regulatory bounds modeled as 0.'),
 ('ip_haymans_london_dry_gin', 'Hayman''s London Dry Gin', 'spirit', 'Hayman''s', 'london dry gin', 'specific_product',
  null, 41.2, null, null, null, 'not_applicable', 0, null, 0, null, null,
  '{"eu_max_sweetening_g_l":0.1}', '{}', '{}',
  'ABV 41.2% per producer product page; London gin sweetening limit 0.1 g/L (EU 2019/787 Annex I(22)).',
  'high', 'secondary', 'ABV taken from the producer page as indexed; confirm against the bottle in hand.'),
 ('ip_angostura_aromatic_bitters', 'Angostura Aromatic Bitters', 'other', 'Angostura', 'aromatic bitters', 'specific_product',
  null, 44.7, null, null, null, 'not_applicable', null, null, null, null, null,
  '{}', '{}', '{"sugar":"not published"}',
  'ABV 44.7% per state liquor listings. Sugar content not published by the producer.',
  'high', 'secondary', 'Usually dosed in dashes (~1 mL, not standardized); sugar unknown and trace at dash doses.'),
 ('ip_coca_cola_classic_us', 'Coca-Cola Original (US, HFCS)', 'carbonated_mixer', 'Coca-Cola', 'cola', 'specific_product',
  null, 0, null, null, null, 'not_applicable', 10.99, null, null, null, null,
  '{"sweetener":"high fructose corn syrup","sugar_g_per_355ml":39}', '{"acidulant":"phosphoric acid (TA not published)"}', '{}',
  'Official US nutrition facts: 39 g total sugars per 12 fl oz (355 mL) = 10.99 g/100 mL.', 'high', 'official',
  'Mexican Coca-Cola (cane sugar) is a different product and is not mapped here.'),
 ('ip_cola_generic', 'Cola - Regular (sugar-sweetened), Product Unspecified', 'carbonated_mixer', null, 'cola', 'literature_range',
  null, 0, null, null, null, 'not_applicable', null, 9.94, null, null, null,
  '{"total_g_100g":9.94,"fructose_g_100g":5.84,"glucose_g_100g":4.10,"sucrose_g_100g":0,"source":"USDA FDC 174852"}', '{"acidulant":"phosphoric acid typical"}',
  '{"note":"brand and sweetener vary; diet colas are ~0"}',
  'USDA FDC 174852 Beverages, carbonated, cola, regular: 9.94 g total sugars/100 g.', 'medium', 'official',
  'Per 100 g; density not yet sourced. Diet/zero colas must not map here.'),
 ('ip_ginger_beer_unspecified', 'Ginger Beer - Product Unspecified', 'carbonated_mixer', null, 'ginger beer', 'generic',
  null, null, null, null, null, 'not_applicable', null, null, null, null, null,
  '{"resolution_required":"product-specific sugar"}', '{}', '{"drivers":["brand","sweetener","dry vs sweet style"]}',
  'Generic category only.', 'low', 'derived',
  'Resolve the product: ginger beer sugar varies widely by brand and style.'),
 ('ip_pineapple_juice_unsweetened', 'Pineapple Juice - Canned/Bottled, Unsweetened', 'fruit_juice', null, 'pineapple juice', 'literature_range',
  null, 0, null, null, null, 'not_applicable', null, 9.98, null, null, null,
  '{"total_g_100g":9.98,"fructose_g_100g":3.81,"glucose_g_100g":4.65,"sucrose_g_100g":1.53,"source":"USDA FDC 169947"}', '{}',
  '{"drivers":["variety","processing","fresh vs canned"]}',
  'USDA FDC 169947 Pineapple juice, canned or bottled, unsweetened: 9.98 g total sugars/100 g.', 'medium', 'official',
  'Per 100 g; density and titratable acidity not yet sourced.'),
 ('ip_tomato_juice_canned', 'Tomato Juice - Canned, Salted', 'other', null, 'tomato juice', 'literature_range',
  null, 0, null, null, null, 'not_applicable', null, 2.58, null, null, null,
  '{"total_g_100g":2.58,"fructose_g_100g":1.33,"glucose_g_100g":1.25,"source":"USDA FDC 170458"}', '{}',
  '{"sodium_mg_100g":253}',
  'USDA FDC 170458 Tomato juice, canned, with salt added: 2.58 g total sugars/100 g; sodium 253 mg/100 g.', 'medium', 'official',
  'Per 100 g; density and titratable acidity not yet sourced.'),
 ('ip_egg_white_raw', 'Egg White - Raw, Fresh', 'other', null, 'egg white', 'literature_range',
  null, 0, null, null, null, 'not_applicable', null, 0.71, 0, null, null,
  '{"total_g_100g":0.71,"source":"USDA FDC 172183"}', '{}', '{"sodium_mg_100g":166}',
  'USDA FDC 172183 Egg, white, raw, fresh: 0.71 g total sugars/100 g.', 'high', 'official',
  'Texture/foam ingredient; sugar negligible. "1 egg white" counts need a volume/mass (~30 mL) to be included.'),
 ('ip_cranberry_juice_cocktail', 'Cranberry Juice Cocktail - Bottled (sweetened)', 'fruit_juice', null, 'cranberry juice cocktail', 'literature_range',
  null, 0, null, null, null, 'not_applicable', null, 11.9, null, null, null,
  '{"total_g_100g":11.9,"fructose_g_100g":4.97,"glucose_g_100g":6.79,"sucrose_g_100g":0,"source":"USDA FDC 171903"}', '{}',
  '{"note":"100% cranberry juice is a different ingredient"}',
  'USDA FDC 171903 Cranberry juice cocktail, bottled: 11.9 g total sugars/100 g.', 'medium', 'official',
  'Per 100 g; density and titratable acidity not yet sourced. Plain "cranberry juice" is not mapped here.')
on conflict (key) do nothing;

-- ---------------------------------------------------------------- evidence
insert into phg_mix.formulation_evidence (record_type, record_key, source_key, url, locator, evidence_role, note) values
 ('ingredient_profile','ip_simple_1_1_weight','src_brix_sg_table',null,'50.00 Brix: apparent SG 1.23202 (20/20 C)','calculation_basis','density for g/100 mL'),
 ('ingredient_profile','ip_simple_1_1_volume','src_brix_sg_table',null,'48.00 Brix: apparent SG 1.22106','calculation_basis','density for g/100 mL'),
 ('ingredient_profile','ip_rich_2_1_weight','src_brix_sg_table',null,'66.50 / 66.80 Brix: 1.32820 / 1.33007 (interpolated)','calculation_basis','density for g/100 mL'),
 ('ingredient_profile','ip_rich_2_1_volume','src_brix_sg_table',null,'65.00 / 65.30 Brix: 1.31905 / 1.32089 (interpolated)','calculation_basis','density for g/100 mL'),
 ('ingredient_profile','ip_simple_1_1_basis_unspecified','src_brix_sg_table',null,'48 and 50 Brix rows','calculation_basis','range endpoints'),
 ('ingredient_profile','ip_simple_1_1_basis_unspecified','src_diffords',null,'1:1 by volume ~48 Brix (existing claim fc_simple_volume_brix)','supporting',null),
 ('ingredient_profile','ip_rich_2_1_basis_unspecified','src_brix_sg_table',null,'65.0-66.8 Brix rows','calculation_basis','range endpoints'),
 ('ingredient_profile','ip_rich_2_1_basis_unspecified','src_diffords',null,'2:1 by volume ~65.1 Brix (existing claim fc_simple_volume_brix)','supporting',null),
 ('ingredient_profile','ip_lemon_juice_working','src_usda_fdc_sr_legacy','https://fdc.nal.usda.gov/food-details/167747/nutrients','FDC 167747','supporting','sugars 2.52 g/100 g'),
 ('ingredient_profile','ip_lime_juice_working','src_usda_fdc_sr_legacy','https://fdc.nal.usda.gov/food-details/168156/nutrients','FDC 168156','supporting','sugars 1.69 g/100 g'),
 ('ingredient_profile','ip_vodka_generic','src_ttb_27cfr_5_142',null,'Table, (1) Vodka','primary','<= 2 g/L sugar, <= 1 g/L citric acid'),
 ('ingredient_profile','ip_ketel_one_vodka','src_ttb_27cfr_5_142',null,'Table, (1) Vodka','supporting','sugar/acid bounds'),
 ('ingredient_profile','ip_ketel_one_vodka','src_state_liquor_listings','https://www.ohlq.com/liquor/vodka/ketel-one-vodka','Ketel One Vodka listing','primary','40% ABV'),
 ('ingredient_profile','ip_london_dry_gin_generic','src_eu_2019_787',null,'Annex I (22)(a)(v), (b)','primary','0.1 g/L sweetening max; 37.5% min ABV'),
 ('ingredient_profile','ip_haymans_london_dry_gin','src_haymans_official',null,'product page','primary','41.2% ABV'),
 ('ingredient_profile','ip_haymans_london_dry_gin','src_eu_2019_787',null,'Annex I (22)(a)(v)','supporting','sweetening limit'),
 ('ingredient_profile','ip_bourbon_generic','src_ttb_27cfr_5_143',null,'Table 1 to paragraph (c), types (2) and (5)','primary','no coloring/flavoring/blending materials for bourbon'),
 ('ingredient_profile','ip_straight_rye_generic','src_ttb_27cfr_5_143',null,'Table 1 to paragraph (c), type (5)','primary','no coloring/flavoring/blending materials'),
 ('ingredient_profile','ip_rye_whiskey_generic','src_ttb_27cfr_5_143',null,'Table 1 to paragraph (c), type (2)','context','blending materials permitted for non-straight rye'),
 ('ingredient_profile','ip_bourbon_or_rye_generic','src_ttb_27cfr_5_143',null,'Table 1 to paragraph (c), types (2) and (5)','context',null),
 ('ingredient_profile','ip_tequila_generic','src_nom_006_tequila',null,'Section 4.1 Mellowing','primary','additives <= 1% of total weight'),
 ('ingredient_profile','ip_angostura_aromatic_bitters','src_state_liquor_listings','https://www.abc.virginia.gov/products/cordials/angostura-bitters','Angostura Bitters listing','primary','44.7% ABV'),
 ('ingredient_profile','ip_coca_cola_classic_us','src_coca_cola_us_nutrition',null,'Nutrition facts, 12 fl oz','primary','39 g total sugars'),
 ('ingredient_profile','ip_cola_generic','src_usda_fdc_sr_legacy','https://fdc.nal.usda.gov/food-details/174852/nutrients','FDC 174852','primary','9.94 g/100 g'),
 ('ingredient_profile','ip_pineapple_juice_unsweetened','src_usda_fdc_sr_legacy','https://fdc.nal.usda.gov/food-details/169947/nutrients','FDC 169947','primary','9.98 g/100 g'),
 ('ingredient_profile','ip_tomato_juice_canned','src_usda_fdc_sr_legacy','https://fdc.nal.usda.gov/food-details/170458/nutrients','FDC 170458','primary','2.58 g/100 g'),
 ('ingredient_profile','ip_egg_white_raw','src_usda_fdc_sr_legacy','https://fdc.nal.usda.gov/food-details/172183/nutrients','FDC 172183','primary','0.71 g/100 g'),
 ('ingredient_profile','ip_cranberry_juice_cocktail','src_usda_fdc_sr_legacy','https://fdc.nal.usda.gov/food-details/171903/nutrients','FDC 171903','primary','11.9 g/100 g')
on conflict do nothing;

-- ---------------------------------------------------------------- claim: Brix is per mass, recipes are per volume
insert into phg_mix.formulation_claims (key, topic, claim_type, statement, quantitative, conditions, limitations, confidence, verification, status) values
 ('fc_brix_mass_vs_volume', 'brix', 'calculation_rule',
  'Brix is grams of sucrose per 100 g of solution; recipes dose syrup by volume, so grams per 100 mL = Brix x density. A 50 Brix syrup (density ~1.23 g/mL at 20 C) carries ~61.5 g sucrose per 100 mL, not 50.',
  '{"formula":"sugar_g_100ml = brix x density_g_ml","examples":{"50_brix":{"density_g_ml":1.2298,"sugar_g_100ml":61.49},"66.7_brix":{"density_g_ml":1.3269,"sugar_g_100ml":88.46}}}',
  '{"temperature_c":20,"matrix":"sucrose-water"}',
  'Density values are for pure sucrose-water at 20 C; other sugars, acids and ethanol change density.', 'high', 'derived', 'active')
on conflict (key) do nothing;
insert into phg_mix.formulation_evidence (record_type, record_key, source_key, locator, evidence_role) values
 ('claim','fc_brix_mass_vs_volume','src_brix_sg_table','50 and 66.5-66.8 Brix rows','calculation_basis')
on conflict do nothing;

-- ---------------------------------------------------------------- aliases (recipe wording -> profile)
-- Brand-named lines map to the brand profile when one exists, otherwise DOWN to the generic profile (never sideways).
insert into phg_mix.ingredient_profile_aliases (alias, profile_key, alias_type) values
 ('simple syrup (1:1)','ip_simple_1_1_basis_unspecified','recipe_term'),
 ('simple syrup 1:1','ip_simple_1_1_basis_unspecified','recipe_term'),
 ('rich sugar syrup (2:1)','ip_rich_2_1_basis_unspecified','recipe_term'),
 ('rich sugar syrup 2:1','ip_rich_2_1_basis_unspecified','recipe_term'),
 ('rich simple syrup','ip_rich_2_1_basis_unspecified','recipe_term'),
 ('rich syrup','ip_rich_2_1_basis_unspecified','recipe_term'),
 ('rich sugar syrup','ip_rich_2_1_basis_unspecified','recipe_term'),
 ('rock candy syrup (rich 2:1 sugar syrup)','ip_rich_2_1_basis_unspecified','recipe_term'),
 ('rich sugar syrup (2:1, 65 brix)','ip_rich_2_1_volume','recipe_term'),
 ('vodka','ip_vodka_generic','normalized_term'),
 ('vodka (wodka)','ip_vodka_generic','recipe_term'),
 ('vodka (belvedere)','ip_vodka_generic','recipe_term'),
 ('vodka (suntory haku)','ip_vodka_generic','recipe_term'),
 ('vodka (ketel one)','ip_ketel_one_vodka','brand'),
 ('vodka (ketel one), from freezer','ip_ketel_one_vodka','brand'),
 ('ketel one','ip_ketel_one_vodka','brand'),
 ('gin','ip_gin_generic','normalized_term'),
 ('dry gin','ip_gin_generic','recipe_term'),
 ('juniper-forward gin','ip_gin_generic','recipe_term'),
 ('plymouth gin','ip_gin_generic','recipe_term'),
 ('fords gin','ip_gin_generic','recipe_term'),
 ('gin (fords)','ip_gin_generic','recipe_term'),
 ('gin (el bart)','ip_gin_generic','recipe_term'),
 ('london dry gin','ip_london_dry_gin_generic','normalized_term'),
 ('london dry gin (hayman''s)','ip_haymans_london_dry_gin','brand'),
 ('london dry gin (hayman''s), from freezer','ip_haymans_london_dry_gin','brand'),
 ('bourbon','ip_bourbon_generic','normalized_term'),
 ('bourbon whiskey','ip_bourbon_generic','recipe_term'),
 ('bourbon (buffalo trace)','ip_bourbon_generic','recipe_term'),
 ('bourbon (elijah craig)','ip_bourbon_generic','recipe_term'),
 ('bourbon (colonel e.h. taylor small batch)','ip_bourbon_generic','recipe_term'),
 ('bourbon (jim beam black)','ip_bourbon_generic','recipe_term'),
 ('bourbon (45% abv)','ip_bourbon_generic','recipe_term'),
 ('maker''s mark bourbon','ip_bourbon_generic','recipe_term'),
 ('jefferson''s reserve bourbon','ip_bourbon_generic','recipe_term'),
 ('cask-strength bourbon (booker''s)','ip_bourbon_generic','recipe_term'),
 ('rye whiskey','ip_rye_whiskey_generic','normalized_term'),
 ('straight rye whiskey (50% abv)','ip_straight_rye_generic','recipe_term'),
 ('bourbon or rye','ip_bourbon_or_rye_generic','recipe_term'),
 ('bourbon or rye whiskey','ip_bourbon_or_rye_generic','recipe_term'),
 ('bourbon (or rye whiskey)','ip_bourbon_or_rye_generic','recipe_term'),
 ('bourbon (or rye)','ip_bourbon_or_rye_generic','recipe_term'),
 ('rye or bourbon','ip_bourbon_or_rye_generic','recipe_term'),
 ('tequila','ip_tequila_generic','normalized_term'),
 ('blanco tequila','ip_tequila_generic','recipe_term'),
 ('silver tequila','ip_tequila_generic','recipe_term'),
 ('reposado tequila','ip_tequila_generic','recipe_term'),
 ('100% agave tequila','ip_tequila_generic','recipe_term'),
 ('tequila 100% agave','ip_tequila_generic','recipe_term'),
 ('tequila (100% agave)','ip_tequila_generic','recipe_term'),
 ('tequila (inexpensive)','ip_tequila_generic','recipe_term'),
 ('tequila (ocho plata preferred)','ip_tequila_generic','recipe_term'),
 ('blanco tequila (100% agave, high quality)','ip_tequila_generic','recipe_term'),
 ('blanco tequila (patrón silver)','ip_tequila_generic','recipe_term'),
 ('blanco tequila (cascahuín blanco)','ip_tequila_generic','recipe_term'),
 ('blanco tequila (el tesoro blanco)','ip_tequila_generic','recipe_term'),
 ('blanco tequila (milagro preferred)','ip_tequila_generic','recipe_term'),
 ('blanco tequila (tapatío blanco)','ip_tequila_generic','recipe_term'),
 ('reposado tequila (patrón reposado)','ip_tequila_generic','recipe_term'),
 ('reposado tequila (el tesoro)','ip_tequila_generic','recipe_term'),
 ('reposado tequila (espolón)','ip_tequila_generic','recipe_term'),
 ('triple sec (cointreau)','ip_cointreau_unique','brand'),
 ('freshly squeezed lemon juice','ip_lemon_juice_working','recipe_term'),
 ('persian lime juice','ip_lime_juice_working','recipe_term'),
 ('fresh orange juice','ip_orange_juice_working','recipe_term'),
 ('orange juice, chilled','ip_orange_juice_working','recipe_term'),
 ('pineapple juice','ip_pineapple_juice_unsweetened','normalized_term'),
 ('unsweetened pineapple juice','ip_pineapple_juice_unsweetened','recipe_term'),
 ('tomato juice','ip_tomato_juice_canned','normalized_term'),
 ('tomato juice, thick','ip_tomato_juice_canned','recipe_term'),
 ('mix: tomato juice','ip_tomato_juice_canned','recipe_term'),
 ('house mix: tomato juice','ip_tomato_juice_canned','recipe_term'),
 ('egg white','ip_egg_white_raw','normalized_term'),
 ('cola','ip_cola_generic','normalized_term'),
 ('coca-cola','ip_coca_cola_classic_us','brand'),
 ('ginger beer','ip_ginger_beer_unspecified','normalized_term'),
 ('ginger beer (thomas henry)','ip_ginger_beer_unspecified','recipe_term'),
 ('cranberry juice cocktail (ocean spray)','ip_cranberry_juice_cocktail','recipe_term'),
 ('cranberry juice cocktail','ip_cranberry_juice_cocktail','normalized_term'),
 ('angostura bitters','ip_angostura_aromatic_bitters','normalized_term'),
 ('angostura aromatic bitters','ip_angostura_aromatic_bitters','brand'),
 ('distilled water','ip_water','recipe_term'),
 ('filtered water','ip_water','recipe_term'),
 ('seltzer','ip_club_soda','recipe_term'),
 ('soda water (thomas henry)','ip_club_soda','recipe_term'),
 ('soda water (thomas henry), chilled','ip_club_soda','recipe_term')
on conflict do nothing;
